steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/agentic-log-attacker:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/agentic-log-attacker:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'agentic-log-attacker'
  - '--image'
  - 'gcr.io/$PROJECT_ID/agentic-log-attacker:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated' # Adjust as needed for authentication
images:
- 'gcr.io/$PROJECT_ID/agentic-log-attacker:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
